### ISSUE TITLE
Not very descriptive error messages

### ISSUE THREAD

**Issue by nminaya** [OkGoDoIt/OpenAI-API-dotnet#1]
I was curious about GPT-3 and I found this project/library so I decided to try it. But when I run the example code snippet I get a NullReferenceException:

![image](https://user-images.githubusercontent.com/7952888/95692829-adc28980-0bf6-11eb-995f-9a1cc1822525.png)

Not sure what is happening, maybe it needs some API key or something. But it will be nice if the error message was a little more descriptive.

**Comment by OkGoDoIt** [comment]
Hmm, I agree that is not very helpful.  There should be descriptive errors, but possibly I missed something.  Let me try to reproduce it to figure out what's going on.  To clarify, do you have API keys, perhaps in a `.openai` file or in an environment variable?

**Comment by OkGoDoIt** [comment]
From my testing, it appears that you did not provide API authentication, and then the library did not raise a very descriptive exception.  I just added better error handling for this situation, so the above should raise an `AuthenticationException` rather than a generic `NullReferenceException`.  I will publish the updated package soon.  In the meantime, please refer to [the auth section of the readme](https://github.com/OkGoDoIt/OpenAI-API-dotnet#authentication) for details on how to provide your API keys.

This library is just a wrapper around the OpenAI API, so you need to have an account with OpenAI and pass your API keys to this library for it all to work.  Let me know if you have any more problems, I'll do my best to help!

**Comment by nminaya** [comment]
@OkGoDoIt Yeah I assumed that the error was something related with the API keys. I have submitted a request to OpenAI to create an account. I'll close this issue.
