### ISSUE TITLE
Managing Tokens

### ISSUE THREAD

**Issue by Daenks** [OkGoDoIt/OpenAI-API-dotnet#115]
For my application, I'm running into issues with having too many tokens:

`"message": "This model's maximum context length is 4097 tokens. However, your messages resulted in 4123 tokens. Please reduce the length of the messages.",`

This library doesn't seem to currently have any way to manage the chat.Messages collection other than "Append" actions. I'd like to be able to prune the conversation to make room for new interactions within the same chat. 

The most simple idea would be to remove the oldest message (I think this is what the Chat UI at https://chat.openai.com/chat/ does). But I have more specific ideas for my application.

Is something like this in the roadmap? Could it be added?

**Comment by OkGoDoIt** [comment]
In general this library has been a thin wrapper around the OpenAI Rest API.  Since their API doesn't really have a way to handle tokenization or estimating context limits, this library also does not.  But the `Conversation` class is my first attempt at adding a higher-level abstraction.  Good point about it becoming useless once there is too much history.

I'm not sure the best way to solve this.  I suppose automatically dropping the oldest messages could work, however usually people give the most important instruction context in the first messages, so that may have suboptimal results.  This is a real problem and I'd love to have more input on the best way to handle it.  Thank you for bringing it up @Daenks.

**Comment by Daenks** [comment]
Its been months and I've keep learning AI, the only additional info I have is that there seems to be three main ways the ecosystem handles this:
1) Stop at limit - The conversation ends at the token limit.
2) Keep the system prompt and the first user message, truncate middle
3) Maintain a rolling window and truncate past messages

(these are directly copy and pasted from inside LMStudio)

**Comment by OkGoDoIt** [comment]
Hey @Daenks, I addressed this in [version 1.8](https://github.com/OkGoDoIt/OpenAI-API-dotnet/releases/tag/v1.8) released December 6th.

Details at https://github.com/OkGoDoIt/OpenAI-API-dotnet#Conversation-History-Context-Length-Management

Basically:

1. If the context length is too long, it will automatically remove the oldest non-system messages from the chat history and try to resubmit. 
2. You can override this behavior by implementing `chat.OnTruncationNeeded` or setting `chat.AutoTruncateOnContextLengthExceeded = false`
3. You can also now manually edit the chat message history list, it is no longer readonly
