### ISSUE TITLE
[Request] Add support for gpt-4o model

### ISSUE THREAD

**Issue by kamilk91** [OkGoDoIt/OpenAI-API-dotnet#215]

**Comment by glienard** [comment]
@kamilk91 Added it in my pull request or you can get it at: https://github.com/glienard/OpenAI-API-dotnet

**Comment by spppaul** [comment]
Please merge this ASAP @kamilk91

**Comment by spppaul** [comment]
https://github.com/OkGoDoIt/OpenAI-API-dotnet/pull/214

**Comment by scara1701** [comment]
I've added omni for now by extending the Model class in my project.

`
    public class AIModelExtended : Model
    {
        public static Model GPT4_Omni => new Model("gpt-4o") { OwnedBy = "openai" };
    }
`

**Comment by ghost** [comment]
Does anyone know what the hold up is on getting this done?

**Comment by OkGoDoIt** [comment]
I’m unfortunately not allowed to announce the details publicly for another week or two, but I promise it’ll be worth the wait. There’s gonna be a lot better and more official support coming soon. Keep an eye on the Microsoft blogs 😉

In the meantime, you can always pass in the model name as a string rather than using the strongly typed models class. Just use the model name identifier string that’s in the [official OpenAI API docs](https://platform.openai.com/docs/models). There’s an implicit cast of string to `Model`.

For example:
```csharp
var chat = api.Chat.CreateConversation();
chat.Model = "gpt-4o";
```

**Comment by scottaddie** [comment]
> Does anyone know what the hold up is on getting this done?

Here's the Microsoft blog post Roger mentioned above: https://devblogs.microsoft.com/dotnet/openai-dotnet-library/

**Comment by OkGoDoIt** [comment]
As @scottaddie mentioned, it's official! Microsoft is launching an official library, which means full API coverage and up-to-date models going forward.  More details in #211 and at the blog at https://devblogs.microsoft.com/dotnet/openai-dotnet-library/
