### ISSUE TITLE
When is the Image API supported?

### ISSUE THREAD

**Issue by mrt3389** [OkGoDoIt/OpenAI-API-dotnet#45]
When is the Image API supported?

**Comment by OkGoDoIt** [comment]
Hey @mrt3389, I'm looking forward to adding DALL-E as well as other new API endpoints, but I'm super busy with my day job these days so I don't know when I'll have a chance.  If you want to take a pass at implementing it, I'm open to a PR.  Otherwise it will probably be at least a couple more weeks.

**Comment by gotmike** [comment]
i can hop on this once i'm done with the finetuning, which is what i'm working on now. if we go the DI route, i'll need to update to support DI along the way as well.

**Comment by stonelv** [comment]
I'm trying to add DALL-E endpoints based on this project's structure. Will push a request later. Hope that could help.

**Comment by OkGoDoIt** [comment]
This was added with #50 :-D  Will be pushed to NuGet as part of v1.6
